### ISSUE TITLE
My server crash after your last commit  

### ISSUE THREAD

**Issue by gsarfati** [Cellarise/loopback-connector-sendgrid#7]
Hello ! Thanks for your connector, but after last commit , my server use your last release and i have this : 

TypeError: Cannot create data source "sendgrid": Cannot initialize connector "SendgridConnector": sendGridLib is not a function
  at new SendgridConnector (/var/app/current/node_modules/loopback-connector-sendgrid/lib/sendgrid.js:21:21)
  at Function.SendgridConnector.initialize (/var/app/current/node_modules/loopback-connector-sendgrid/lib/sendgrid.js:30:26)
  at DataSource.setup (/var/app/current/node_modules/loopback-datasource-juggler/lib/datasource.js:337:19)
  at new DataSource (/var/app/current/node_modules/loopback-datasource-juggler/lib/datasource.js:114:8)
  at Registry.createDataSource (/var/app/current/node_modules/loopback/lib/registry.js:354:12)
  at dataSourcesFromConfig (/var/app/current/node_modules/loopback/lib/application.js:435:19)
  at EventEmitter.app.dataSource (/var/app/current/node_modules/loopback/lib/application.js:233:14)
  at /var/app/current/node_modules/loopback-boot/lib/executor.js:188:9
  at /var/app/current/node_modules/loopback-boot/lib/executor.js:279:5
  at Array.forEach (native)
  at forEachKeyedObject (/var/app/current/node_modules/loopback-boot/lib/executor.js:278:20)
  at setupDataSources (/var/app/current/node_modules/loopback-boot/lib/executor.js:178:3)
  at execute (/var/app/current/node_modules/loopback-boot/lib/executor.js:37:3)
  at bootLoopBackApp (/var/app/current/node_modules/loopback-boot/index.js:145:3)
  at Object.<anonymous> (/var/app/current/server/server.coffee:16:1)
  at Object.<anonymous> (/var/app/current/server/server.coffee:1:1)
  at Module._compile (module.js:409:26)
  at Object.exports.run (/var/app/current/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/var/app/current/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/var/app/current/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/var/app/current/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/var/app/current/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3

I try to fix dependencie to 1.2.2 , I hope this work again !

**Comment by gsarfati** [comment]
Ok It's work again :)

Please Guys if you push new release and its not retro compatible update the version to the next number like 2.0.0 , because your connector is amazing but my app in production crash during two hours today.. and my boss was not happy because we lost money during two hours... 

Good luck guys and thanks for your connector ! you deserve my star ;)

**Comment by JohnMBarry** [comment]
Sorry for the problem caused by the last commit. I had upgraded from sendgrid 2.0.0 to 3.0.4. Release 2.0.0 recognises this change.
Thanks for your support.

**Comment by chuckcarpenter** [comment]
@JohnMBarry are there other config changes needed for this major version change? 1.2.4 and 2.0.0 result in the same issue as noted above. The issue is on the lib import, which is no longer the same and breaks this connector. e.g., `var sendGridLib = require('sendgrid').SendGrid;` fails.

**Comment by JohnMBarry** [comment]
@chuckcarpenter could you try release 2.0.1 which is based on the sendgrid web APIv3 config. Note change to use mail_settings and tracking_settings JSON objects for sendgrid setting configuration

**Comment by JohnMBarry** [comment]
@chuckcarpenter could you try release 2.0.2

**Comment by chuckcarpenter** [comment]
@JohnMBarry I'll try that out this evening, thanks!

**Comment by chuckcarpenter** [comment]
@JohnMBarry still getting an error, but not exactly the same. Need to see if I can track that down.

**Comment by JohnMBarry** [comment]
Please advise if this needs to be reopened
