### ISSUE TITLE
Cannot initialize connector "SendgridConnector": sendGridLib is not a function

### ISSUE THREAD

**Issue by tunghoang91** [Cellarise/loopback-connector-sendgrid#8]
This's error when i integrate connector sendgrid.

`TypeError: Cannot create data source "sendgrid": Cannot initialize connector "SendgridConnector": sendGridLib is not a function
    at new SendgridConnector (/Users/tunght/work/freelancer/ducna-project-git/apm-api/node_modules/loopback-connector-sendgrid/lib/sendgrid.js:21:21)
    at Function.SendgridConnector.initialize (/Users/tunght/work/freelancer/ducna-project-git/apm-api/node_modules/loopback-connector-sendgrid/lib/sendgrid.js:30:26)
    at DataSource.setup (/Users/tunght/work/freelancer/ducna-project-git/apm-api/node_modules/loopback-datasource-juggler/lib/datasource.js:337:19)
    at new DataSource (/Users/tunght/work/freelancer/ducna-project-git/apm-api/node_modules/loopback-datasource-juggler/lib/datasource.js:114:8)
    at Registry.createDataSource (/Users/tunght/work/freelancer/ducna-project-git/apm-api/node_modules/loopback/lib/registry.js:349:12)
    at dataSourcesFromConfig (/Users/tunght/work/freelancer/ducna-project-git/apm-api/node_modules/loopback/lib/application.js:434:19)
    at EventEmitter.app.dataSource (/Users/tunght/work/freelancer/ducna-project-git/apm-api/node_modules/loopback/lib/application.js:233:14)
    at /Users/tunght/work/freelancer/ducna-project-git/apm-api/node_modules/loopback-boot/lib/executor.js:188:9
    at /Users/tunght/work/freelancer/ducna-project-git/apm-api/node_modules/loopback-boot/lib/executor.js:279:5
    at Array.forEach (native)
    at forEachKeyedObject (/Users/tunght/work/freelancer/ducna-project-git/apm-api/node_modules/loopback-boot/lib/executor.js:278:20)
    at setupDataSources (/Users/tunght/work/freelancer/ducna-project-git/apm-api/node_modules/loopback-boot/lib/executor.js:178:3)
    at execute (/Users/tunght/work/freelancer/ducna-project-git/apm-api/node_modules/loopback-boot/lib/executor.js:37:3)
    at bootLoopBackApp (/Users/tunght/work/freelancer/ducna-project-git/apm-api/node_modules/loopback-boot/index.js:145:3)
    at Object.<anonymous> (/Users/tunght/work/freelancer/ducna-project-git/apm-api/server/server.js:21:1)
    at Module._compile (module.js:413:34)`

**Comment by JohnMBarry** [comment]
Could you try v2.0.1

**Comment by mharkus** [comment]
2.0.1 also fails. You now have to use .SendGrid when initializing sendgrid lib.

sendGridLib.SendGrid(settings.api_key, settings.options);

**Comment by JohnMBarry** [comment]
Completed test steps. Please try 2.0.2
